name: Run Ansible Playbook
on:
  workflow_dispatch:
jobs:
  run-playbook:
    runs-on: ubuntu-latest
    env:
        NUID: ${{ secrets.NUID }}
    steps:
    - name: Display
      run: |
        echo $NUID 
